/*
 * This file is generated by jOOQ.
 */
package com.miven.springboot.jooq.repository;


import com.miven.springboot.jooq.repository.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in demo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"unchecked", "rawtypes" })
public class Tables {

    /**
     * 用户表
     */
    public static final User USER = com.miven.springboot.jooq.repository.tables.User.USER;
}
